# Test against recent major versions of eslint.
eslint:
  jobs:
    - versions:
        include: "^9.0.0"
        mode: latest-majors
      peerDependencies: "@eslint/js@9"
      node: "^18.18.0 || ^20.9.0 || >=21.1.0"
    - versions:
        include: "^10.0.0"
        mode: latest-majors
      peerDependencies: "@eslint/js@10"
      node: "^20.19.0 || ^22.13.0 || >=24"
